model:
  classifier_name: "bert-base-uncased"
  num_classes: 77
  max_length: 128

paths:
  tokenizer_path: "saved_model/tokenizer"
  model_path: "saved_model/bert_intent_classifier.pt"
  label_names_path: "saved_model/label_names.json"

  reference_data_path: "data/reference/train_df.csv"
  production_data_path: "data/production/test_df.csv"
  
  production_data_concept_path: "data/production/concept_drift.parquet"
  production_data_data_path: "data/production/data_drift.parquet"
  production_data_label_path: "data/production/label_drift.parquet"
  inference_logs_path: "data/inference_logs"

training:
  batch_size: 16
  epochs: 8
  lr: 2e-5

monitoring:
  text_drift_threshold: 0.5
  label_drift_threshold: 0.15